services:
  n8n:
    image: n8nio/n8n:2.2.5
    container_name: n8n
    ports:
      - "443:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=change-me
      - N8N_SECURE_COOKIE=false

      # Allow AI / community nodes
      - N8N_ENABLE_COMMUNITY_NODES=true
      - N8N_ENABLE_EXTERNAL_NODES=true

      # (Optional, useful for POC)
      - N8N_NODE_ENV=production

    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_files:/files
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgv
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
#      - "443:8000"

volumes:
  pgdata:
