[project]
name = "sof-n8n-pocs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling>=2.66.0",
    "fastapi>=0.128.0",
    "python-multipart>=0.0.21",
    "uvicorn>=0.40.0",
]
