[project]
name = "sof-poc1-n8n-fiches"
version = "0.1.0"
description = "Fast API for expose 'surnet/alpine-node-wkhtmltopdf'"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling>=2.65.0",
    "fastapi>=0.124.0",
    "httpx>=0.28.1",
    "uvicorn>=0.38.0",
]
